-- +goose Up
-- +goose StatementBegin
CREATE SCHEMA IF NOT EXISTS nixie;
CREATE SCHEMA IF NOT EXISTS config;

CREATE TABLE nixie.contact_form (
    contact_form_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL,
    description TEXT NOT NULL,
    domain TEXT NOT NULL DEFAULT 'nixiepixel.com'
);

CREATE TABLE config.social_app_type (
    social_app_type TEXT PRIMARY KEY
);

CREATE TABLE config.social_app (
    app_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    social_app_type TEXT NOT NULL REFERENCES config.social_app_type(social_app_type) ON DELETE CASCADE,
    client_id TEXT NOT NULL,
    secret TEXT NOT NULL,
    callback_url TEXT
);

CREATE UNIQUE INDEX idx_social_app_type ON config.social_app (social_app_type);

CREATE TABLE config.user_social (
    user_social_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    app_id BIGINT NOT NULL REFERENCES config.social_app(app_id),
    user_id TEXT NOT NULL,
    meta_data JSONB,
    access_token TEXT,
    secret_token TEXT
);

INSERT INTO config.social_app_type (social_app_type) VALUES
('DISCORD'), ('FACEBOOK'), ('INSTAGRAM'), ('TWITCH'), ('TWITTER'), ('YOUTUBE');
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS config.user_social;
DROP TABLE IF EXISTS config.social_app;
DROP TABLE IF EXISTS config.social_app_type;
DROP TABLE IF EXISTS nixie.contact_form;
DROP SCHEMA IF EXISTS config;
DROP SCHEMA IF EXISTS nixie;
-- +goose StatementEnd
