services:
  app:
    external_links:
      - shared_psql
    networks:
      - shared_backend
    image: ghcr.io/osalt/gb-www-nixie:main
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./db/migrations:/db/migrations


networks:
  shared_backend:
    name: shared_backend
    external: true
