// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ConfigSocialApp struct {
	AppID         int64
	SocialAppType string
	ClientID      string
	Secret        string
	CallbackUrl   pgtype.Text
}

type ConfigSocialAppType struct {
	SocialAppType string
}

type ConfigUserSocial struct {
	UserSocialID int64
	AppID        int64
	UserID       string
	MetaData     []byte
	AccessToken  pgtype.Text
	SecretToken  pgtype.Text
}

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

type NixieContactForm struct {
	ContactFormID int64
	Email         string
	Description   string
	Domain        string
}
