// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const getSocialAppByType = `-- name: GetSocialAppByType :one
SELECT app_id, social_app_type, client_id, secret, callback_url FROM config.social_app
WHERE social_app_type = $1
`

func (q *Queries) GetSocialAppByType(ctx context.Context, socialAppType string) (ConfigSocialApp, error) {
	row := q.db.QueryRow(ctx, getSocialAppByType, socialAppType)
	var i ConfigSocialApp
	err := row.Scan(
		&i.AppID,
		&i.SocialAppType,
		&i.ClientID,
		&i.Secret,
		&i.CallbackUrl,
	)
	return i, err
}

const getUserSocialByApp = `-- name: GetUserSocialByApp :one
SELECT user_social_id, app_id, user_id, meta_data, access_token, secret_token FROM config.user_social
WHERE app_id = $1
`

func (q *Queries) GetUserSocialByApp(ctx context.Context, appID int64) (ConfigUserSocial, error) {
	row := q.db.QueryRow(ctx, getUserSocialByApp, appID)
	var i ConfigUserSocial
	err := row.Scan(
		&i.UserSocialID,
		&i.AppID,
		&i.UserID,
		&i.MetaData,
		&i.AccessToken,
		&i.SecretToken,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT contact_form_id, email, description, domain FROM nixie.contact_form
WHERE domain = $1
`

func (q *Queries) ListContacts(ctx context.Context, domain string) ([]NixieContactForm, error) {
	rows, err := q.db.Query(ctx, listContacts, domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NixieContactForm
	for rows.Next() {
		var i NixieContactForm
		if err := rows.Scan(
			&i.ContactFormID,
			&i.Email,
			&i.Description,
			&i.Domain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocialApps = `-- name: ListSocialApps :many
SELECT app_id, social_app_type, client_id, secret, callback_url FROM config.social_app
`

func (q *Queries) ListSocialApps(ctx context.Context) ([]ConfigSocialApp, error) {
	rows, err := q.db.Query(ctx, listSocialApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigSocialApp
	for rows.Next() {
		var i ConfigSocialApp
		if err := rows.Scan(
			&i.AppID,
			&i.SocialAppType,
			&i.ClientID,
			&i.Secret,
			&i.CallbackUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
