port: "8080"
database_url: ""
blog_urls:
  - https://www.geekbeacon.org/tag/geekbeacon-fest/rss/
  - https://www.geekbeacon.org/tag/geeksabroad/rss/

newsletters:
  - name: "geekbeacon"
    description: "geekbeacon news and updates. Stay current with all the community news!"
    url: "https://geekbeacon.org/#/portal"
